/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSkillsRouteImport } from './routes/app.skills'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNavigateRouteImport } from './routes/app.navigate'
import { Route as AppMentorshipRouteImport } from './routes/app.mentorship'
import { Route as AppLearnRouteImport } from './routes/app.learn'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'
import { Route as AppFacultyRouteImport } from './routes/app.faculty'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppEventsIndexRouteImport } from './routes/app.events.index'
import { Route as AppClubsIndexRouteImport } from './routes/app.clubs.index'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as AppClubsClubIdRouteImport } from './routes/app.clubs.$clubId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNavigateRoute = AppNavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorshipRoute = AppMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultyRoute = AppFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsIndexRoute = AppClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsClubIdRoute = AppClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/faculty': typeof AppFacultyRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/learn': typeof AppLearnRoute
  '/app/mentorship': typeof AppMentorshipRoute
  '/app/navigate': typeof AppNavigateRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/': typeof AppIndexRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/faculty': typeof AppFacultyRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/learn': typeof AppLearnRoute
  '/app/mentorship': typeof AppMentorshipRoute
  '/app/navigate': typeof AppNavigateRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app': typeof AppIndexRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/clubs': typeof AppClubsIndexRoute
  '/app/events': typeof AppEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/faculty': typeof AppFacultyRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/learn': typeof AppLearnRoute
  '/app/mentorship': typeof AppMentorshipRoute
  '/app/navigate': typeof AppNavigateRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/': typeof AppIndexRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/ai'
    | '/app/announcements'
    | '/app/faculty'
    | '/app/feedback'
    | '/app/learn'
    | '/app/mentorship'
    | '/app/navigate'
    | '/app/profile'
    | '/app/settings'
    | '/app/skills'
    | '/app/'
    | '/app/clubs/$clubId'
    | '/app/events/$eventId'
    | '/app/clubs/'
    | '/app/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/ai'
    | '/app/announcements'
    | '/app/faculty'
    | '/app/feedback'
    | '/app/learn'
    | '/app/mentorship'
    | '/app/navigate'
    | '/app/profile'
    | '/app/settings'
    | '/app/skills'
    | '/app'
    | '/app/clubs/$clubId'
    | '/app/events/$eventId'
    | '/app/clubs'
    | '/app/events'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/ai'
    | '/app/announcements'
    | '/app/faculty'
    | '/app/feedback'
    | '/app/learn'
    | '/app/mentorship'
    | '/app/navigate'
    | '/app/profile'
    | '/app/settings'
    | '/app/skills'
    | '/app/'
    | '/app/clubs/$clubId'
    | '/app/events/$eventId'
    | '/app/clubs/'
    | '/app/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/navigate': {
      id: '/app/navigate'
      path: '/navigate'
      fullPath: '/app/navigate'
      preLoaderRoute: typeof AppNavigateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentorship': {
      id: '/app/mentorship'
      path: '/mentorship'
      fullPath: '/app/mentorship'
      preLoaderRoute: typeof AppMentorshipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faculty': {
      id: '/app/faculty'
      path: '/faculty'
      fullPath: '/app/faculty'
      preLoaderRoute: typeof AppFacultyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/': {
      id: '/app/clubs/'
      path: '/clubs'
      fullPath: '/app/clubs/'
      preLoaderRoute: typeof AppClubsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/$clubId': {
      id: '/app/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/app/clubs/$clubId'
      preLoaderRoute: typeof AppClubsClubIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppFacultyRoute: typeof AppFacultyRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppLearnRoute: typeof AppLearnRoute
  AppMentorshipRoute: typeof AppMentorshipRoute
  AppNavigateRoute: typeof AppNavigateRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClubsClubIdRoute: typeof AppClubsClubIdRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppClubsIndexRoute: typeof AppClubsIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppFacultyRoute: AppFacultyRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppLearnRoute: AppLearnRoute,
  AppMentorshipRoute: AppMentorshipRoute,
  AppNavigateRoute: AppNavigateRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClubsClubIdRoute: AppClubsClubIdRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppClubsIndexRoute: AppClubsIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
